### ISSUE TITLE
 error when transmitting periscope

### ISSUE THREAD

**Issue by eliasestrada** [goatie999/nginx-rtmps-docker#1]
Excellent work done.

I am using Digitalocean with the Cyberpanel administrator which includes a section to manage Docker when I enter the Environment 'tab of the docker and I add the URL and KEY data of the preset stream services where I want to send the signal everything works perfect, but when I enter the data of a different service for example Periscope and start the docker. in Periscope it does not start the transmission.

https://imgur.com/F1tDRo2

logs
https://imgur.com/8wE1LhF

**Comment by goatie999** [comment]
Periscope isn't a service that I've ever looked or tested with this setup but I'll take a look at some point if there's anything specific about Pexip's service in order for it to be included.

However, can I ask... as you've forked the code, did you add all the other code needed to add an additional service? or just add Environment Variables to the 'Dockerfile'?

**Comment by eliasestrada** [comment]
sorry i didn't change that data that's why it didn't work .. now it works perfect.
